### ISSUE TITLE
Won't load character info

### ISSUE THREAD

**Issue by karlwilbur** [dasilva333/TowerGhostForDestiny#684]
This was working, but it crashed (as it *always* does after about 15 minutes) and after a restart it won't load any character data.

Here is all of the output:
```
karl@karl-S400CA [17:07:49] [/opt/tower_ghost_for_destiny] 
-> % /opt/tower_ghost_for_destiny/tower_ghost_for_destiny
[6519:1206/170805:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[6519:1206/170811:INFO:CONSOLE(387)] ""New manifest available, but an earlier update attempt failed. Will not download."", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js (387)
[6519:1206/170816:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'completionValue' of undefined
    at file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:3050:88
    at Function.m.map.m.collect (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:127:2566)
    at Object.Item.init (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:3049:47)
    at Object.Item (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:2868:10)
    at file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:4243:41
    at Function.m.each.m.forEach (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:127:2350)
    at Object.complete (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:4242:19)
    at Object.$.ajax.complete (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:561:30)
    at j (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:2:27295)
    at Object.k.fireWith (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:2:28108)
[6519:1206/170816:INFO:CONSOLE(3050)] "Uncaught TypeError: Cannot read property 'completionValue' of undefined", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js (3050)
[6519:1206/170816:INFO:CONSOLE(105)] ""crash reported Uncaught TypeError: Cannot read property 'completionValue' of undefined"", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/4.extras.js (105)
[6519:1206/170816:INFO:CONSOLE(106)] "", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/4.extras.js (106)
[6519:1206/170816:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'completionValue' of undefined
    at file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:3050:88
    at Function.m.map.m.collect (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:127:2566)
    at Object.Item.init (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:3049:47)
    at Object.Item (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:2868:10)
    at file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:4243:41
    at Function.m.each.m.forEach (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:127:2350)
    at Object.complete (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:4242:19)
    at Object.$.ajax.complete (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:561:30)
    at j (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:2:27295)
    at Object.k.fireWith (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:2:28108)
[6519:1206/170816:INFO:CONSOLE(3050)] "Uncaught TypeError: Cannot read property 'completionValue' of undefined", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js (3050)
[6519:1206/170816:INFO:CONSOLE(105)] ""crash reported Uncaught TypeError: Cannot read property 'completionValue' of undefined"", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/4.extras.js (105)
[6519:1206/170816:INFO:CONSOLE(106)] "", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/4.extras.js (106)
[6519:1206/170816:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'completionValue' of undefined
    at file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:3050:88
    at Function.m.map.m.collect (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:127:2566)
    at Object.Item.init (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:3049:47)
    at Object.Item (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:2868:10)
    at file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:4243:41
    at Function.m.each.m.forEach (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:127:2350)
    at Object.complete (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:4242:19)
    at Object.$.ajax.complete (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js:561:30)
    at j (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:2:27295)
    at Object.k.fireWith (file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/1.libraries.js:2:28108)
[6519:1206/170816:INFO:CONSOLE(3050)] "Uncaught TypeError: Cannot read property 'completionValue' of undefined", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/3.tower_ghost.js (3050)
[6519:1206/170816:INFO:CONSOLE(105)] ""crash reported Uncaught TypeError: Cannot read property 'completionValue' of undefined"", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/4.extras.js (105)
[6519:1206/170816:INFO:CONSOLE(106)] "", source: file:///tmp/.org.chromium.Chromium.jSzqK1/www/resources/4.extras.js (106)
[6519:1206/170827:ERROR:cert_verify_proc_nss.cc(886)] CERT_PKIXVerifyCert for destinydb.com failed err=-8181
```

Here's a screenshot of the window:
![screenshot from 2016-12-06 17 13 52](https://cloud.githubusercontent.com/assets/55618/20946122/93be9588-bbd7-11e6-8210-3a3a837f7d1a.png)

This may be related to #682

**Comment by karlwilbur** [comment]
It says that "New manifest available, but an earlier update attempt failed. Will not download." but I've tried deleting everything and reinstalling from ZIP file and it says the exact same thing.

**Comment by dasilva333** [comment]
I see you're on 3.6.9 try disabling and enabling Auto Updates to see if it clears the cache. Otherwise you'll have to find the cache directory and clear it manually. I'm guessing you used this file:

List under Linux 32bit
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/tgd-linux-x32.zip?raw=true

 Under downloads here:
http://towerghostfordestiny.com/index.php/downloads/

I just tried it myself and it seems to work fine updated from 3.9.0.9 to 3.9.3.3 on it's own.

Good luck

**Comment by karlwilbur** [comment]
Yeah, I'm on 64bit though FWIW. I'll give it a shot in a couple hours.

Where is the cache directory?

--
Karl Wilbur
513-322-2481
karl@karlwilbur.net

**Comment by Techneeqx** [comment]
How do we clear the cache directory?

**Comment by karlwilbur** [comment]
Trying to "find the cache directory and clear it manually" doesn't actually do anything. I am seeing the *excact* same behavior on *every* systems I have (3 desktops and 4 laptops, all running Ubuntu 14.04 or 16.04). Every time it is exactly the same. If anything is cached, it is most definitely not on the client end and thus completely out of my control. 

Here are screenshots.

Immediatly after install:
![image](https://cloud.githubusercontent.com/assets/55618/21343113/44a041ea-c663-11e6-9d52-1e3e09444905.png)

After logging into PSN:
![image](https://cloud.githubusercontent.com/assets/55618/21343181/8d6fa8d4-c663-11e6-9e71-22fdfab4df4c.png)

**Comment by Techneeqx** [comment]
I'm having the same issue except on an Android OS. I'm happy to help and try to troubleshoot different tests.

**Comment by Techneeqx** [comment]
Can we qualify this as a bug?
